/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

/**
 *
 * @author Nicolas
 */
public class candidatosExistentes extends javax.swing.JPanel {

    /**
     * Creates new form candidatosExistentes
     */
    public candidatosExistentes() {
        initComponents();
        mensaje.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        candidatosTB = new javax.swing.JTable();
        seleccionarB = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();

        jLabel1.setText("Por favor selecciona uno de los siguientes candidatos:");

        candidatosTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Gonzalo P.", "Cook", "95%", "900   USD", "NO"},
                {"Maria M.", "Cook", "81%", "1000 USD", "SI"},
                {"Laura L.", "Head Chef", "51%", "2000 USD", "NO"},
                {"Ryan G.", "Waiter", "17%", "500   USD", "NO"}
            },
            new String [] {
                "Nombre", "Carrera", "Aptitud", "Salario Proyectado", "Ex-Empleado"
            }
        ));
        jScrollPane1.setViewportView(candidatosTB);

        seleccionarB.setText("Seleccionar");
        seleccionarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarBActionPerformed(evt);
            }
        });

        mensaje.setText("Empleado Preseleccionado Satisfactoriamente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(mensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seleccionarB)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionarB)
                    .addComponent(mensaje))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarBActionPerformed
        mensaje.setVisible(true);
    }//GEN-LAST:event_seleccionarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable candidatosTB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JButton seleccionarB;
    // End of variables declaration//GEN-END:variables
}
