/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Entidad.EmpleadoEntidad;
import Entidad.ListaEmpleados;

/**
 *
 * @author Nicolas
 */
public class framePrincipal extends javax.swing.JFrame {
      
    private buscarEmpleadoNovedad buscarN = new buscarEmpleadoNovedad();
    private retirarempleado retirar = new retirarempleado();
    private cargos elegircargo = new cargos();
    private lista nomina = new lista();
    public framePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        novedadesB = new javax.swing.JButton();
        contratacionB = new javax.swing.JButton();
        retirarB = new javax.swing.JButton();
        listarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR System");

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        novedadesB.setText("Novedades");
        novedadesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novedadesBActionPerformed(evt);
            }
        });
        jToolBar1.add(novedadesB);

        contratacionB.setText("Contratacion");
        contratacionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratacionBActionPerformed(evt);
            }
        });
        jToolBar1.add(contratacionB);

        retirarB.setText("Retirar Empleado");
        retirarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarBActionPerformed(evt);
            }
        });
        jToolBar1.add(retirarB);

        listarB.setText("Listar Empleados");
        listarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBActionPerformed(evt);
            }
        });
        jToolBar1.add(listarB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novedadesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novedadesBActionPerformed
      panelPrincipal.setVisible(false);
      panelPrincipal.removeAll();
      panelPrincipal.add(buscarN);
      panelPrincipal.setVisible(true);   
    }//GEN-LAST:event_novedadesBActionPerformed

    private void retirarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarBActionPerformed
      panelPrincipal.setVisible(false);
      panelPrincipal.removeAll();
      panelPrincipal.add(retirar);
      panelPrincipal.setVisible(true); 
    }//GEN-LAST:event_retirarBActionPerformed

    private void listarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBActionPerformed
      panelPrincipal.setVisible(false);
      panelPrincipal.removeAll();
      panelPrincipal.add(nomina);
      panelPrincipal.setVisible(true); 
    }//GEN-LAST:event_listarBActionPerformed

    private void contratacionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratacionBActionPerformed
      panelPrincipal.setVisible(false);
      panelPrincipal.removeAll();
      panelPrincipal.add(elegircargo);
      panelPrincipal.setVisible(true); 
    }//GEN-LAST:event_contratacionBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePrincipal().setVisible(true);
            }
        });
    }
    public void inicializar(){
       
 
    EmpleadoEntidad uno=new EmpleadoEntidad();
    EmpleadoEntidad dos=new EmpleadoEntidad();
    EmpleadoEntidad tres=new EmpleadoEntidad();
    EmpleadoEntidad cuatro=new EmpleadoEntidad();
    EmpleadoEntidad cinco=new EmpleadoEntidad();
    
    
        uno.setARL("1020");
        uno.setActivo(true);
        uno.setApellido("CHAVES");
        uno.setCesantias(23);
        uno.setContactoDeEmergencia(305612321);
        uno.setDireccion("Avenida calle 22#15-69");
        uno.setEPS("SaludCoop");
        uno.setEdad(21);
        uno.setId("1030685411");
        uno.setNombre("ANDRES");
        uno.setPensiones(900000);
        
        dos.setARL("1030");
        dos.setActivo(true);
        dos.setApellido("CASTAÑEDA");
        dos.setCesantias(24);
        dos.setContactoDeEmergencia(306798545);
        dos.setDireccion("AVENIDA LAS FERIAS#70-05");
        dos.setEPS("SALUDTOTAL");
        dos.setEdad(19);
        dos.setId("1019146963");
        dos.setNombre("SEBASTIAN");
        dos.setPensiones(900000);
        
        tres.setARL("1040");
        tres.setActivo(true);
        tres.setApellido("CARO");
        tres.setCesantias(25);
        tres.setContactoDeEmergencia(10232131);
        tres.setDireccion("AV.PRIMERADEMAYO#70-22");
        tres.setEPS("VIVASALUD");
        tres.setEdad(25);
        tres.setId("1013647467");
        tres.setNombre("NICOLAS");
        tres.setPensiones(1200000);
        
        ListaEmpleados lista=new ListaEmpleados();
        lista.AñadirEmpleado(uno);
        lista.AñadirEmpleado(dos);
        lista.AñadirEmpleado(tres);
        
    }
    


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contratacionB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton listarB;
    private javax.swing.JButton novedadesB;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton retirarB;
    // End of variables declaration//GEN-END:variables
}
