/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

/**
 *
 * @author Nicolas
 */
public class NoveltyChooseView extends javax.swing.JPanel {

    private NoveltyView aumento = new NoveltyView();
    private NoveltyDecreaseView disminucion = new NoveltyDecreaseView();

    /**
     * Creates new form elegirTipoNovedad
     */
    public NoveltyChooseView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        aumentoB = new javax.swing.JButton();
        disminucionB = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        aumentoB.setText("Ingresad Novedad de Aumento");
        aumentoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentoBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(101, 166, 0, 131);
        add(aumentoB, gridBagConstraints);

        disminucionB.setText("Ingresar Novedad de Disminución");
        disminucionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disminucionBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 166, 94, 131);
        add(disminucionB, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void aumentoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentoBActionPerformed
        this.setVisible(false);
        this.removeAll();
        this.add(aumento);
        this.setVisible(true);
    }//GEN-LAST:event_aumentoBActionPerformed

    private void disminucionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disminucionBActionPerformed
        this.setVisible(false);
        this.removeAll();
        this.add(disminucion);
        this.setVisible(true);
    }//GEN-LAST:event_disminucionBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aumentoB;
    private javax.swing.JButton disminucionB;
    // End of variables declaration//GEN-END:variables
}
