/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Entidad.EmployeeEntity;
import dao.EmpleadoDAO;
import java.awt.GridBagConstraints;
import java.awt.Label;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicolas
 */
public class NoveltySearchView extends javax.swing.JPanel {

    private NoveltyChooseView elegirN = new NoveltyChooseView();
    private static EmployeeEntity aux = new EmployeeEntity();

    /**
     * Creates new form buscarEmpleadoNovedad
     */
    public NoveltySearchView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        documentoTF = new javax.swing.JTextField();
        buscarB = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Número de documento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(117, 123, 0, 0);
        add(jLabel1, gridBagConstraints);

        documentoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(114, 41, 0, 108);
        add(documentoTF, gridBagConstraints);

        buscarB.setText("Buscar Empleado");
        buscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 190, 93, 0);
        add(buscarB, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBActionPerformed
        EmpleadoDAO dao = new EmpleadoDAO();
        String documento = this.documentoTF.getText();
        //aux = PrincipalFrame.listaEmpleados.getEmpleado(documento);
        aux = dao.obtener(documento);
        if (aux == null) {
            JOptionPane.showMessageDialog(null, "No existe el empleado");
        } else {
            if(aux.isActivo()){
            jLabel1.setVisible(false);
            jLabel1.removeAll();
            this.setVisible(false);
            this.removeAll();
            this.add(elegirN);
            this.setVisible(true);    
            }
            else{
                JOptionPane.showMessageDialog(null, "el empleado no esta activo");
            }
        }


    }//GEN-LAST:event_buscarBActionPerformed

    private void documentoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoTFActionPerformed

    public static EmployeeEntity getAux() {
        return aux;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarB;
    private javax.swing.JTextField documentoTF;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
