/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Entidad.EmployeeEntity;

/**
 *
 * @author Nicolas
 */
public class NoveltyDecreaseView extends javax.swing.JPanel {

    /**
     * Creates new form disminucionP
     */
    public NoveltyDecreaseView() {
        initComponents();
        confirmLB.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        novedadesCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cantidadTF = new javax.swing.JTextField();
        aceptarB = new javax.swing.JButton();
        cancelarB = new javax.swing.JButton();
        confirmLB = new javax.swing.JLabel();

        jLabel1.setText("Tipo de novedad");

        novedadesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Incapacidad", "Faltas", "Pago Adelantado", "Vacaciones" }));
        novedadesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novedadesCBActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad a cambiar");

        aceptarB.setText("Aceptar");
        aceptarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBActionPerformed(evt);
            }
        });

        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });

        confirmLB.setText("Novedad Agregada con éxito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(novedadesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25)
                        .addComponent(cantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aceptarB)
                        .addGap(84, 84, 84)
                        .addComponent(cancelarB)))
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmLB)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(novedadesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(cantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aceptarB)
                    .addComponent(cancelarB))
                .addGap(18, 18, 18)
                .addComponent(confirmLB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void novedadesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novedadesCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novedadesCBActionPerformed

    private void aceptarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBActionPerformed
        EmployeeEntity aux = NoveltySearchView.getAux();
        switch (novedadesCB.getSelectedIndex()) {
            case 0:
                aux.getNovedades().setIncapacidad(aux.getNovedades().getIncapacidad()
                        + Integer.parseInt(cantidadTF.getText()));
                break;
            case 1:
                aux.getNovedades().setFaltas(aux.getNovedades().getFaltas()
                        + Integer.parseInt(cantidadTF.getText()));
                break;
            case 2:
                aux.getNovedades().setAdelanto(aux.getNovedades().getAdelanto()
                        + Integer.parseInt(cantidadTF.getText()));
                break;
            case 3:
                aux.getNovedades().setDiasDeVacaciones(aux.getNovedades().getDiasDeVacaciones()
                        + Integer.parseInt(cantidadTF.getText()));
                break;
        }
        PrincipalFrame.listaEmpleados.retirarEmpleado(aux.getId());
        PrincipalFrame.listaEmpleados.AñadirEmpleado(aux);
        System.out.println(PrincipalFrame.listaEmpleados.getEmpleado(aux.getId()).toString());
        System.out.println(PrincipalFrame.listaEmpleados.getEmpleado(aux.getId()).getNovedades().toString());

        confirmLB.setVisible(true);
    }//GEN-LAST:event_aceptarBActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        this.setVisible(false);
        this.removeAll();
    }//GEN-LAST:event_cancelarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarB;
    private javax.swing.JButton cancelarB;
    private javax.swing.JTextField cantidadTF;
    private javax.swing.JLabel confirmLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> novedadesCB;
    // End of variables declaration//GEN-END:variables
}
