/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Entidad.EmployeeEntity;
import dao.EmpleadoDAO;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolas
 */
public class PrincipalFrame extends javax.swing.JFrame {

    
    

    public PrincipalFrame() {
        initComponents();        

    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }

    public void addRowtoJtable() {
        EmpleadoDAO dao = new EmpleadoDAO();
        DefaultTableModel model = (DefaultTableModel) RosterView.listaT.getModel();
        Object rowData[] = new Object[11];
        ArrayList<EmployeeEntity> listaEmpleados = dao.getlista();
        for (int i = 0; i < listaEmpleados.size(); i++) {
            rowData[0] = listaEmpleados.get(i).getNombre();
            rowData[1] = listaEmpleados.get(i).getApellido();
            rowData[2] = listaEmpleados.get(i).getIdentificacion();
            rowData[3] = listaEmpleados.get(i).getEdad();
            rowData[4] = listaEmpleados.get(i).getARL();
            rowData[5] = listaEmpleados.get(i).getEPS();
            rowData[6] = listaEmpleados.get(i).getContactoDeEmergencia();
            rowData[7] = listaEmpleados.get(i).getDireccion();
            rowData[8] = listaEmpleados.get(i).getCargo().getNombre();
            rowData[9] = listaEmpleados.get(i).getCargo().getSueldo();
            rowData[10] = listaEmpleados.get(i).isActivo();
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        novedadesB = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        contratacionB = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        retirarB = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        listarB = new javax.swing.JButton();
        SalarioB = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR System");
        setSize(new java.awt.Dimension(500, 1000));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMargin(new java.awt.Insets(10, 10, 10, 10));

        novedadesB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        novedadesB.setText("Novedades");
        novedadesB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        novedadesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novedadesBActionPerformed(evt);
            }
        });
        jToolBar1.add(novedadesB);
        jToolBar1.add(jSeparator1);

        contratacionB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        contratacionB.setText("Contratacion");
        contratacionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratacionBActionPerformed(evt);
            }
        });
        jToolBar1.add(contratacionB);
        jToolBar1.add(jSeparator2);

        retirarB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        retirarB.setText("Retirar Empleado");
        retirarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarBActionPerformed(evt);
            }
        });
        jToolBar1.add(retirarB);
        jToolBar1.add(jSeparator3);

        listarB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        listarB.setText("Listar Empleados");
        listarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBActionPerformed(evt);
            }
        });
        jToolBar1.add(listarB);

        SalarioB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SalarioB.setText("Calcular Salario Empleado");
        SalarioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioBActionPerformed(evt);
            }
        });
        jToolBar1.add(SalarioB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método para actualizar el contenido del panelPrincipal
    private void ActualizarGUI(JComponent component1, JComponent component2) {
        component1.removeAll();
        component1.add(component2);
        cleanButtonStyles();
        component1.revalidate();
        component1.repaint();
    }

    private void paintButtonActive(JButton button) {
        button.requestFocus();
        button.setFont(new Font("SansSerif", Font.BOLD, 14));
    }

    private void cleanButtonStyles() {
        for (int i = 0; i < 7; i++) {
            Component comp = jToolBar1.getComponent(i);
            if (comp instanceof JButton) {
                JButton button = (JButton) comp;
                button.setFont(new Font("SansSerif", Font.PLAIN, 14));
            }
        }
    }

    private void novedadesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novedadesBActionPerformed
        NoveltySearchView buscarN = new NoveltySearchView();
        javax.swing.SwingUtilities.invokeLater(() -> {
            ActualizarGUI(panelPrincipal, buscarN);
            paintButtonActive(novedadesB);
        });

    }//GEN-LAST:event_novedadesBActionPerformed

    private void retirarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarBActionPerformed
        RemoveView retirar = new RemoveView();
        javax.swing.SwingUtilities.invokeLater(() -> {
            ActualizarGUI(panelPrincipal, retirar);
            paintButtonActive(retirarB);
        });
    }//GEN-LAST:event_retirarBActionPerformed

    private void listarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBActionPerformed
        RosterView nomina = new RosterView();
        javax.swing.SwingUtilities.invokeLater(() -> {
            ActualizarGUI(panelPrincipal, nomina);
            paintButtonActive(listarB);
            addRowtoJtable();
        });
    }//GEN-LAST:event_listarBActionPerformed

    private void contratacionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratacionBActionPerformed
        //Acá el constructor de la vista está modificado para propagar el panel principal a todos los nodos hijos. Esto podría ser fácilmente evitable
        //usando interfaces, sin embargo, Swing es una shit y no conozco muy bien su AST como para meterle mano
        SelectView2 elegircargo = new SelectView2(panelPrincipal);
        javax.swing.SwingUtilities.invokeLater(() -> {
            ActualizarGUI(panelPrincipal, elegircargo);
            paintButtonActive(contratacionB);
        });
    }//GEN-LAST:event_contratacionBActionPerformed

    private void SalarioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioBActionPerformed
        SalaryView salario = new SalaryView();
        javax.swing.SwingUtilities.invokeLater(() -> {
            ActualizarGUI(panelPrincipal, salario);
            paintButtonActive(SalarioB);
            addRowtoJtable();
        });
    }//GEN-LAST:event_SalarioBActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalarioB;
    private javax.swing.JButton contratacionB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton listarB;
    private javax.swing.JButton novedadesB;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton retirarB;
    // End of variables declaration//GEN-END:variables
}
