/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.CalculateSalaryControl;
import Control.RemoveControl;
import Entidad.EmployeeEntity;
import Entidad.EmployeesList;
import dao.EmpleadoDAO;
import javax.swing.JOptionPane;
import sun.reflect.generics.visitor.Reifier;

/**
 *
 * @author Nicolas
 */
public class RemoveView extends javax.swing.JPanel {

    /**
     * Creates new form retirarempleado
     */
    public RemoveView() {
        initComponents();
        // mensaje.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscarTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Identificacion");

        jLabel2.setText("Retirar Empleado");

        jButton1.setText("Retirar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(buscarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String RetirarId = buscarTF.getText();
        EmployeeEntity Retirado = new EmployeeEntity();
        EmpleadoDAO dao = new EmpleadoDAO();
        double Salario = 0;
        //Retirado = PrincipalFrame.listaEmpleados.getEmpleado(RetirarId);
        Retirado = dao.obtener(RetirarId);
        if (Retirado == null) {
            JOptionPane.showMessageDialog(null, "No existe el empleado");

        } else {
            if (Retirado.isActivo()) {
                RemoveControl r = new RemoveControl();
                int descicion = JOptionPane.showConfirmDialog(null, "Seguro descea retirar al empleado " + Retirado.getNombre() + " " + Retirado.getApellido());
                if (descicion == JOptionPane.YES_OPTION) {
                    Salario = r.RemoveEmployee(Retirado);
                    JOptionPane.showMessageDialog(null, "El empleado ha sido retirado y su liquidacion es de: " + Salario + " $");

                }
            } else {
                JOptionPane.showMessageDialog(null, "el empleado ya no esta activo");

            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
