/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

/**
 *
 * @author Nicolas
 */
public class retirarempleado extends javax.swing.JPanel {

    /**
     * Creates new form retirarempleado
     */
    public retirarempleado() {
        initComponents();
        mensaje.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscarTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        retirarT = new javax.swing.JTable();
        retirarB = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();

        jLabel1.setText("Buscar Empleado");

        retirarT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Anderson C.", "Presidente", "40", "3000 usd"},
                {"Marco B.", "Head Chef", "23", "1500 usd"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Cargo", "Edad", "Salario"
            }
        ));
        jScrollPane1.setViewportView(retirarT);

        retirarB.setText("Retirar");
        retirarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarBActionPerformed(evt);
            }
        });

        mensaje.setText("Empleado Retirado Con Éxito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(buscarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mensaje)
                        .addGap(18, 18, 18)
                        .addComponent(retirarB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retirarB)
                    .addComponent(mensaje))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void retirarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarBActionPerformed
        mensaje.setVisible(true);
    }//GEN-LAST:event_retirarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JButton retirarB;
    private javax.swing.JTable retirarT;
    // End of variables declaration//GEN-END:variables
}
