/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

/**
 *
 * @author Nicolas
 */
public class seleccionE extends javax.swing.JPanel {
    
private nuevoCan candidato = new nuevoCan();
private candidatosExistentes candidatos = new candidatosExistentes();
    /**
     * Creates new form seleccionE
     */
    public seleccionE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nuevopB = new javax.swing.JButton();
        buscarB = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        nuevopB.setText("Nuevo perfil de empleado");
        nuevopB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevopBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(86, 100, 0, 109);
        add(nuevopB, gridBagConstraints);

        buscarB.setText("Buscar en empleados registrados");
        buscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 100, 98, 109);
        add(buscarB, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void nuevopBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevopBActionPerformed
        this.setVisible(false);
        this.removeAll();
        this.add(candidato);
        this.setVisible(true);
    }//GEN-LAST:event_nuevopBActionPerformed

    private void buscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBActionPerformed
        this.setVisible(false);
        this.removeAll();
        this.add(candidatos);
        this.setVisible(true);
    }//GEN-LAST:event_buscarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarB;
    private javax.swing.JButton nuevopB;
    // End of variables declaration//GEN-END:variables
}
