/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import javax.swing.JComponent;
import javax.swing.JPanel;

/**
 *
 * @author Nicolas
 */
public class SelectView extends javax.swing.JPanel {
    
    private JPanel ParentPanel;

    private SelectView2 select;
     
    public SelectView(JPanel panel) {
        ParentPanel = panel;
        select = new SelectView2(ParentPanel);
        initComponents();
    }
    
    private void ActualizarGUI(JComponent component1, JComponent component2) {
        component1.removeAll();
        component1.add(component2);
        component1.revalidate();
        component1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cargoB = new javax.swing.JButton();
        seleccionCB = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridBagLayout());

        cargoB.setText("Continuar");
        cargoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 153, 119, 0);
        add(cargoB, gridBagConstraints);

        seleccionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Vacante", "Head Chef", "Cook", "Janitor" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(132, 128, 0, 118);
        add(seleccionCB, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cargoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoBActionPerformed
        javax.swing.SwingUtilities.invokeLater(() -> ActualizarGUI(ParentPanel, select));
    }//GEN-LAST:event_cargoBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargoB;
    private javax.swing.JComboBox<String> seleccionCB;
    // End of variables declaration//GEN-END:variables
}
